
services:
  app:
    image: parksofprague:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["--hostname", "0.0.0.0", "--port", "8080"]
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  db_data:
